version: "3.3"
services:
  tm:
    image: traffmonetizer/cli
    container_name: tm
    restart: always
    command: start accept --token avwzQlgwEVb/eoAErZsQBomXZTrL5beDOpK6MVr4mEc= --device-name paas
  peer2profit:
    image: peer2profit/peer2profit_linux:latest
    container_name: peer2profit
    restart: always
    environment:
      - P2P_EMAIL=cecepabd67@gmail.com

